# Generated by Django 5.1.3 on 2024-12-02 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(max_length=2)),
                ('metal_level', models.CharField(max_length=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('rate_area', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZipRateArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=2)),
                ('county_code', models.PositiveIntegerField()),
                ('county_name', models.CharField(max_length=30)),
                ('rate_area', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
